"""
Generate supabase/seed.sql from packages/characters/data/*.json
Populates the claws table with 30 character records.
"""
import json
import os

DATA_DIR = os.path.join(os.path.dirname(__file__), "..", "packages", "characters", "data")
OUTPUT = os.path.join(os.path.dirname(__file__), "..", "supabase", "seed.sql")

# Gender mapping by category (CLAUDE.md §7-11: male/female only in MVP1)
GENDER_BY_CATEGORY = {
    "demon": "male",
    "god": "male",
    "wild": "male",
    "robot": "male",
    "human": "male",
    "goddess": "female",
    "temptress": "female",
    "fluffy": "female",
    "concierge": "female",
    "friend": "female",
}

def escape_sql(s: str) -> str:
    if s is None:
        return "NULL"
    return "'" + s.replace("'", "''") + "'"

def extract_dossier_field(dossier: dict, key: str) -> str:
    val = dossier.get(key, "")
    if isinstance(val, dict):
        return val.get("jp", "") or val.get("en", "") or ""
    return val or ""

def to_pg_array(items: list[str]) -> str:
    escaped = [i.replace("'", "''").replace('"', '\\"') for i in items]
    return "'{" + ",".join(f'"{i}"' for i in escaped) + "}'"

def to_jsonb(obj) -> str:
    return escape_sql(json.dumps(obj, ensure_ascii=False))

def main():
    index_path = os.path.join(DATA_DIR, "index.json")
    with open(index_path, "r", encoding="utf-8") as f:
        index = json.load(f)

    lines = [
        "-- =============================================",
        "-- OPENCLAW Seed Data: 30 Characters (claws table)",
        "-- Generated by scripts/generate-seed-sql.py",
        "-- =============================================",
        "",
        "INSERT INTO public.claws (",
        "  claw_no, name_jp, name_en, name_romaji,",
        "  category, gender, element, origin,",
        "  personality, first_person, tone, catchphrase,",
        "  best_for, industries,",
        "  image_filename, primary_color, accent_color,",
        "  origin_paragraphs, dossier, your_fate_paragraphs,",
        "  quote, daily_routine, oaths, kinsmen,",
        "  system_prompt",
        ") VALUES",
    ]

    values = []
    for entry in index:
        file_path = os.path.join(DATA_DIR, entry["file"])
        with open(file_path, "r", encoding="utf-8") as f:
            char = json.load(f)

        d = char.get("dossier", {})
        gender = GENDER_BY_CATEGORY.get(char["category"], "male")
        element = extract_dossier_field(d, "Element")
        origin_place = extract_dossier_field(d, "Origin")
        personality = d.get("Personality", "")
        first_person = d.get("First Person", "")
        tone = d.get("Tone", "")
        catchphrase = d.get("Catchphrase", "")
        best_for = d.get("Best For", "")
        industries_str = d.get("Industries", "")
        industries = [i.strip() for i in industries_str.split("・") if i.strip()] if industries_str else []

        quote_obj = char.get("quote")
        quote_text = ""
        if quote_obj:
            quote_text = quote_obj.get("text", "") or ""

        val = f"""(
  {char['claw_no']}, {escape_sql(char['name_jp'])}, {escape_sql(char['name_en'])}, {escape_sql(char['name_romaji'])},
  {escape_sql(char['category'])}, {escape_sql(gender)}, {escape_sql(element)}, {escape_sql(origin_place)},
  {escape_sql(personality)}, {escape_sql(first_person)}, {escape_sql(tone)}, {escape_sql(catchphrase)},
  {escape_sql(best_for)}, {to_pg_array(industries)},
  {escape_sql(char['image_filename'])}, {escape_sql(char['primary_color'])}, {escape_sql(char['accent_color'])},
  {to_jsonb(char.get('origin_paragraphs', []))}, {to_jsonb(char.get('dossier', {}))}, {to_jsonb(char.get('your_fate_paragraphs', []))},
  {escape_sql(quote_text)}, {to_jsonb(char.get('daily_routine', []))}, {to_jsonb(char.get('oaths', []))}, {to_jsonb(char.get('kinsmen', []))},
  {escape_sql('')}
)"""
        values.append(val)

    lines.append(",\n".join(values))
    lines.append("ON CONFLICT (claw_no) DO UPDATE SET")
    lines.append("  name_jp = EXCLUDED.name_jp,")
    lines.append("  name_en = EXCLUDED.name_en,")
    lines.append("  name_romaji = EXCLUDED.name_romaji,")
    lines.append("  category = EXCLUDED.category,")
    lines.append("  gender = EXCLUDED.gender,")
    lines.append("  element = EXCLUDED.element,")
    lines.append("  origin = EXCLUDED.origin,")
    lines.append("  personality = EXCLUDED.personality,")
    lines.append("  first_person = EXCLUDED.first_person,")
    lines.append("  tone = EXCLUDED.tone,")
    lines.append("  catchphrase = EXCLUDED.catchphrase,")
    lines.append("  best_for = EXCLUDED.best_for,")
    lines.append("  industries = EXCLUDED.industries,")
    lines.append("  image_filename = EXCLUDED.image_filename,")
    lines.append("  primary_color = EXCLUDED.primary_color,")
    lines.append("  accent_color = EXCLUDED.accent_color,")
    lines.append("  origin_paragraphs = EXCLUDED.origin_paragraphs,")
    lines.append("  dossier = EXCLUDED.dossier,")
    lines.append("  your_fate_paragraphs = EXCLUDED.your_fate_paragraphs,")
    lines.append("  quote = EXCLUDED.quote,")
    lines.append("  daily_routine = EXCLUDED.daily_routine,")
    lines.append("  oaths = EXCLUDED.oaths,")
    lines.append("  kinsmen = EXCLUDED.kinsmen,")
    lines.append("  updated_at = NOW();")

    with open(OUTPUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"Generated {OUTPUT} with {len(values)} character records")

if __name__ == "__main__":
    main()
