-- =============================================
-- OPENCLAW Platform - Academy phrase collection (MVP1)
-- =============================================
-- SPEC-09 §2.1 / §2.2

CREATE TABLE IF NOT EXISTS public.academy_phrase_collection (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  volume INTEGER NOT NULL CHECK (volume BETWEEN 1 AND 8),
  category TEXT NOT NULL,
  phrase TEXT NOT NULL,
  result TEXT,
  related_week INTEGER CHECK (related_week BETWEEN 1 AND 8),
  difficulty TEXT NOT NULL DEFAULT 'beginner' CHECK (difficulty IN ('beginner', 'intermediate', 'advanced')),
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_academy_phrases_volume
  ON public.academy_phrase_collection(volume);

CREATE INDEX IF NOT EXISTS idx_academy_phrases_category
  ON public.academy_phrase_collection(category);

CREATE INDEX IF NOT EXISTS idx_academy_phrases_week
  ON public.academy_phrase_collection(related_week);

ALTER TABLE public.academy_phrase_collection ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "academy_phrases_select_all" ON public.academy_phrase_collection;
CREATE POLICY "academy_phrases_select_all"
  ON public.academy_phrase_collection FOR SELECT
  USING (true);

INSERT INTO public.academy_phrase_collection (volume, category, phrase, result, related_week, difficulty)
VALUES
  (1, 'install', 'このプロジェクトの構成を3分で説明して', '初期理解と環境構築を短時間で進められる', 1, 'beginner'),
  (1, 'install', 'ローカル起動手順を順番に作って', '初期理解と環境構築を短時間で進められる', 1, 'beginner'),
  (1, 'install', '環境変数の不足をチェックして', '初期理解と環境構築を短時間で進められる', 1, 'beginner'),
  (1, 'install', '初学者向けに依存関係を整理して', '初期理解と環境構築を短時間で進められる', 1, 'beginner'),
  (1, 'install', 'このエラーの原因候補を3つ出して', '初期理解と環境構築を短時間で進められる', 1, 'beginner'),
  (1, 'install', 'READMEなしで導入手順を推測して', '初期理解と環境構築を短時間で進められる', 1, 'beginner'),
  (1, 'install', '型エラーの入口ファイルを特定して', '初期理解と環境構築を短時間で進められる', 1, 'beginner'),
  (1, 'install', 'API一覧を抽出して表にして', '初期理解と環境構築を短時間で進められる', 1, 'beginner'),
  (1, 'install', '使っていないファイルを洗い出して', '初期理解と環境構築を短時間で進められる', 1, 'beginner'),
  (1, 'install', 'テスト実行コマンドを全部見つけて', '初期理解と環境構築を短時間で進められる', 1, 'beginner'),
  (1, 'install', '本番前チェックリストを作って', '初期理解と環境構築を短時間で進められる', 1, 'beginner'),
  (1, 'install', 'このコードの責務を一言で要約して', '初期理解と環境構築を短時間で進められる', 1, 'beginner'),
  (1, 'install', 'この関数の入出力を説明して', '初期理解と環境構築を短時間で進められる', 1, 'beginner'),
  (1, 'install', '命名規則の傾向を抽出して', '初期理解と環境構築を短時間で進められる', 1, 'beginner'),
  (1, 'install', '共通化できる処理を探して', '初期理解と環境構築を短時間で進められる', 1, 'beginner'),
  (1, 'install', 'バグ再現手順を短くまとめて', '初期理解と環境構築を短時間で進められる', 1, 'beginner'),
  (1, 'install', '依存アップデートの影響範囲を見積もって', '初期理解と環境構築を短時間で進められる', 1, 'beginner'),
  (1, 'install', 'このPRの確認観点を列挙して', '初期理解と環境構築を短時間で進められる', 1, 'beginner'),
  (1, 'install', '最短で動作確認する方法を提案して', '初期理解と環境構築を短時間で進められる', 1, 'beginner'),
  (2, 'create', '問い合わせフォームを実装して', 'CRUDと認証を含む実装を一気に前進できる', 2, 'beginner'),
  (2, 'create', '会員登録ページを作って', 'CRUDと認証を含む実装を一気に前進できる', 2, 'beginner'),
  (2, 'create', 'ログイン画面にバリデーションを追加して', 'CRUDと認証を含む実装を一気に前進できる', 2, 'beginner'),
  (2, 'create', '管理画面の検索機能を作って', 'CRUDと認証を含む実装を一気に前進できる', 2, 'beginner'),
  (2, 'create', '一覧画面にページネーションを追加して', 'CRUDと認証を含む実装を一気に前進できる', 2, 'beginner'),
  (2, 'create', 'CSVエクスポート機能を作って', 'CRUDと認証を含む実装を一気に前進できる', 2, 'beginner'),
  (2, 'create', 'アップロードAPIを作って', 'CRUDと認証を含む実装を一気に前進できる', 2, 'beginner'),
  (2, 'create', 'Webhook受信エンドポイントを実装して', 'CRUDと認証を含む実装を一気に前進できる', 2, 'beginner'),
  (2, 'create', '通知設定画面を作って', 'CRUDと認証を含む実装を一気に前進できる', 2, 'beginner'),
  (2, 'create', 'プロフィール編集機能を作って', 'CRUDと認証を含む実装を一気に前進できる', 2, 'beginner'),
  (2, 'create', 'パスワード再設定導線を実装して', 'CRUDと認証を含む実装を一気に前進できる', 2, 'beginner'),
  (2, 'create', 'メール認証フローを作って', 'CRUDと認証を含む実装を一気に前進できる', 2, 'beginner'),
  (2, 'create', 'APIレスポンス型を定義して', 'CRUDと認証を含む実装を一気に前進できる', 2, 'beginner'),
  (2, 'create', '入力スキーマをzodで作って', 'CRUDと認証を含む実装を一気に前進できる', 2, 'beginner'),
  (2, 'create', '失敗時トーストを追加して', 'CRUDと認証を含む実装を一気に前進できる', 2, 'beginner'),
  (2, 'create', 'ローディング状態を追加して', 'CRUDと認証を含む実装を一気に前進できる', 2, 'beginner'),
  (2, 'create', '空データ時のUIを追加して', 'CRUDと認証を含む実装を一気に前進できる', 2, 'beginner'),
  (2, 'create', '初回オンボーディング画面を作って', 'CRUDと認証を含む実装を一気に前進できる', 2, 'beginner'),
  (2, 'create', 'アクセス権限チェックを追加して', 'CRUDと認証を含む実装を一気に前進できる', 2, 'beginner'),
  (3, 'design', 'このページをスマホ最適化して', 'UI品質と可読性を保ったまま改善できる', 3, 'intermediate'),
  (3, 'design', 'この画面の余白設計を整えて', 'UI品質と可読性を保ったまま改善できる', 3, 'intermediate'),
  (3, 'design', '色コントラストを改善して', 'UI品質と可読性を保ったまま改善できる', 3, 'intermediate'),
  (3, 'design', 'タイポグラフィを統一して', 'UI品質と可読性を保ったまま改善できる', 3, 'intermediate'),
  (3, 'design', 'カードUIを再利用可能にして', 'UI品質と可読性を保ったまま改善できる', 3, 'intermediate'),
  (3, 'design', 'ダークモードに対応して', 'UI品質と可読性を保ったまま改善できる', 3, 'intermediate'),
  (3, 'design', 'アニメーションを控えめに調整して', 'UI品質と可読性を保ったまま改善できる', 3, 'intermediate'),
  (3, 'design', 'フォームUIを統一して', 'UI品質と可読性を保ったまま改善できる', 3, 'intermediate'),
  (3, 'design', 'エラー表示を目立たせて', 'UI品質と可読性を保ったまま改善できる', 3, 'intermediate'),
  (3, 'design', '成功メッセージの見せ方を改善して', 'UI品質と可読性を保ったまま改善できる', 3, 'intermediate'),
  (3, 'design', 'CTAボタンの配置を最適化して', 'UI品質と可読性を保ったまま改善できる', 3, 'intermediate'),
  (3, 'design', '一覧の視認性を改善して', 'UI品質と可読性を保ったまま改善できる', 3, 'intermediate'),
  (3, 'design', 'アクセシビリティ属性を追加して', 'UI品質と可読性を保ったまま改善できる', 3, 'intermediate'),
  (3, 'design', 'キーボード操作で完結できるようにして', 'UI品質と可読性を保ったまま改善できる', 3, 'intermediate'),
  (3, 'design', '読み込み中スケルトンを追加して', 'UI品質と可読性を保ったまま改善できる', 3, 'intermediate'),
  (3, 'design', 'レスポンシブメニューを作って', 'UI品質と可読性を保ったまま改善できる', 3, 'intermediate'),
  (3, 'design', 'テーブルをモバイル対応して', 'UI品質と可読性を保ったまま改善できる', 3, 'intermediate'),
  (3, 'design', '余計な装飾を削って可読性を上げて', 'UI品質と可読性を保ったまま改善できる', 3, 'intermediate'),
  (3, 'design', 'ブランドトーンに合わせて調整して', 'UI品質と可読性を保ったまま改善できる', 3, 'intermediate'),
  (4, 'function', 'このボタンでAPIを呼び出して', '実運用を意識した堅牢な機能実装にできる', 4, 'intermediate'),
  (4, 'function', '失敗時に再試行処理を入れて', '実運用を意識した堅牢な機能実装にできる', 4, 'intermediate'),
  (4, 'function', '重複送信を防止して', '実運用を意識した堅牢な機能実装にできる', 4, 'intermediate'),
  (4, 'function', 'トランザクション処理を追加して', '実運用を意識した堅牢な機能実装にできる', 4, 'intermediate'),
  (4, 'function', 'Webhook署名検証を実装して', '実運用を意識した堅牢な機能実装にできる', 4, 'intermediate'),
  (4, 'function', 'リトライキューを実装して', '実運用を意識した堅牢な機能実装にできる', 4, 'intermediate'),
  (4, 'function', '監査ログ保存を追加して', '実運用を意識した堅牢な機能実装にできる', 4, 'intermediate'),
  (4, 'function', '検索条件をクエリに同期して', '実運用を意識した堅牢な機能実装にできる', 4, 'intermediate'),
  (4, 'function', 'キャッシュを導入して', '実運用を意識した堅牢な機能実装にできる', 4, 'intermediate'),
  (4, 'function', 'レート制限を追加して', '実運用を意識した堅牢な機能実装にできる', 4, 'intermediate'),
  (4, 'function', '並列処理を安全に実装して', '実運用を意識した堅牢な機能実装にできる', 4, 'intermediate'),
  (4, 'function', 'タイムアウト処理を追加して', '実運用を意識した堅牢な機能実装にできる', 4, 'intermediate'),
  (4, 'function', '外部APIエラーを分類して', '実運用を意識した堅牢な機能実装にできる', 4, 'intermediate'),
  (4, 'function', '入力値を正規化して', '実運用を意識した堅牢な機能実装にできる', 4, 'intermediate'),
  (4, 'function', 'DB保存前に小文字化して', '実運用を意識した堅牢な機能実装にできる', 4, 'intermediate'),
  (4, 'function', 'RLS前提のクエリに修正して', '実運用を意識した堅牢な機能実装にできる', 4, 'intermediate'),
  (4, 'function', 'ジョブ実行結果を記録して', '実運用を意識した堅牢な機能実装にできる', 4, 'intermediate'),
  (4, 'function', '障害時フォールバックを追加して', '実運用を意識した堅牢な機能実装にできる', 4, 'intermediate'),
  (4, 'function', 'feature flagで切り替え可能にして', '実運用を意識した堅牢な機能実装にできる', 4, 'intermediate'),
  (5, 'ai', 'このプロンプトを短く強くして', 'AI応答品質と再現性を高い水準で揃えられる', 5, 'intermediate'),
  (5, 'ai', 'キャラ口調を崩さないようにして', 'AI応答品質と再現性を高い水準で揃えられる', 5, 'intermediate'),
  (5, 'ai', '禁止ワードを避ける再生成を入れて', 'AI応答品質と再現性を高い水準で揃えられる', 5, 'intermediate'),
  (5, 'ai', '回答を3段階で出すようにして', 'AI応答品質と再現性を高い水準で揃えられる', 5, 'intermediate'),
  (5, 'ai', '要約品質を上げる指示を書いて', 'AI応答品質と再現性を高い水準で揃えられる', 5, 'intermediate'),
  (5, 'ai', '曖昧入力に追加質問する設計にして', 'AI応答品質と再現性を高い水準で揃えられる', 5, 'intermediate'),
  (5, 'ai', 'ユーザー意図分類の精度を上げて', 'AI応答品質と再現性を高い水準で揃えられる', 5, 'intermediate'),
  (5, 'ai', '誤回答時の謝罪テンプレを作って', 'AI応答品質と再現性を高い水準で揃えられる', 5, 'intermediate'),
  (5, 'ai', '出力フォーマットをJSON固定にして', 'AI応答品質と再現性を高い水準で揃えられる', 5, 'intermediate'),
  (5, 'ai', 'トークン使用量を抑える指示にして', 'AI応答品質と再現性を高い水準で揃えられる', 5, 'intermediate'),
  (5, 'ai', '根拠付き回答を促すプロンプトにして', 'AI応答品質と再現性を高い水準で揃えられる', 5, 'intermediate'),
  (5, 'ai', '営業文面生成向けに最適化して', 'AI応答品質と再現性を高い水準で揃えられる', 5, 'intermediate'),
  (5, 'ai', 'SNS投稿向けに短文化して', 'AI応答品質と再現性を高い水準で揃えられる', 5, 'intermediate'),
  (5, 'ai', 'LPコピー向けに感情訴求を強めて', 'AI応答品質と再現性を高い水準で揃えられる', 5, 'intermediate'),
  (5, 'ai', 'FAQ回答を丁寧語で統一して', 'AI応答品質と再現性を高い水準で揃えられる', 5, 'intermediate'),
  (5, 'ai', 'Bot人格の一人称を統一して', 'AI応答品質と再現性を高い水準で揃えられる', 5, 'intermediate'),
  (5, 'ai', '危険要求を拒否する文面を入れて', 'AI応答品質と再現性を高い水準で揃えられる', 5, 'intermediate'),
  (5, 'ai', '長文入力を段落分割して扱って', 'AI応答品質と再現性を高い水準で揃えられる', 5, 'intermediate'),
  (5, 'ai', '次アクション提案を必ず付けて', 'AI応答品質と再現性を高い水準で揃えられる', 5, 'intermediate'),
  (6, 'deploy', '本番デプロイ手順をチェックして', 'デプロイ/運用の事故を減らし再現性を上げられる', 6, 'intermediate'),
  (6, 'deploy', 'CIでlint/typecheck/testを強制して', 'デプロイ/運用の事故を減らし再現性を上げられる', 6, 'intermediate'),
  (6, 'deploy', 'migration適用順を検証して', 'デプロイ/運用の事故を減らし再現性を上げられる', 6, 'intermediate'),
  (6, 'deploy', 'ロールバック手順を作って', 'デプロイ/運用の事故を減らし再現性を上げられる', 6, 'intermediate'),
  (6, 'deploy', 'Secrets設定漏れを検出して', 'デプロイ/運用の事故を減らし再現性を上げられる', 6, 'intermediate'),
  (6, 'deploy', 'Cloudflare設定を点検して', 'デプロイ/運用の事故を減らし再現性を上げられる', 6, 'intermediate'),
  (6, 'deploy', 'Supabaseキーの権限を確認して', 'デプロイ/運用の事故を減らし再現性を上げられる', 6, 'intermediate'),
  (6, 'deploy', '監視アラート条件を提案して', 'デプロイ/運用の事故を減らし再現性を上げられる', 6, 'intermediate'),
  (6, 'deploy', '障害時Runbookを作って', 'デプロイ/運用の事故を減らし再現性を上げられる', 6, 'intermediate'),
  (6, 'deploy', 'バックアップ頻度を見直して', 'デプロイ/運用の事故を減らし再現性を上げられる', 6, 'intermediate'),
  (6, 'deploy', '日次バッチ失敗時通知を追加して', 'デプロイ/運用の事故を減らし再現性を上げられる', 6, 'intermediate'),
  (6, 'deploy', 'リリースノートを自動生成して', 'デプロイ/運用の事故を減らし再現性を上げられる', 6, 'intermediate'),
  (6, 'deploy', 'ステージング検証項目を作って', 'デプロイ/運用の事故を減らし再現性を上げられる', 6, 'intermediate'),
  (6, 'deploy', 'デプロイ後ヘルスチェックを追加して', 'デプロイ/運用の事故を減らし再現性を上げられる', 6, 'intermediate'),
  (6, 'deploy', 'API応答時間を計測して', 'デプロイ/運用の事故を減らし再現性を上げられる', 6, 'intermediate'),
  (6, 'deploy', 'キャッシュヘッダを最適化して', 'デプロイ/運用の事故を減らし再現性を上げられる', 6, 'intermediate'),
  (6, 'deploy', 'cron重複実行を防止して', 'デプロイ/運用の事故を減らし再現性を上げられる', 6, 'intermediate'),
  (6, 'deploy', '長時間ジョブを分割して', 'デプロイ/運用の事故を減らし再現性を上げられる', 6, 'intermediate'),
  (6, 'deploy', '運用ログの保管期間を定義して', 'デプロイ/運用の事故を減らし再現性を上げられる', 6, 'intermediate'),
  (7, 'monetize', 'この機能の収益化案を3つ出して', '売上導線と継続率の両面で改善案を作れる', 7, 'advanced'),
  (7, 'monetize', '無料から有料への導線を作って', '売上導線と継続率の両面で改善案を作れる', 7, 'advanced'),
  (7, 'monetize', 'LTVを伸ばす施策を提案して', '売上導線と継続率の両面で改善案を作れる', 7, 'advanced'),
  (7, 'monetize', '解約率を下げる施策を考えて', '売上導線と継続率の両面で改善案を作れる', 7, 'advanced'),
  (7, 'monetize', '紹介制度の訴求文を作って', '売上導線と継続率の両面で改善案を作れる', 7, 'advanced'),
  (7, 'monetize', 'アップセル文面を3パターン作って', '売上導線と継続率の両面で改善案を作れる', 7, 'advanced'),
  (7, 'monetize', '価格表の見せ方を改善して', '売上導線と継続率の両面で改善案を作れる', 7, 'advanced'),
  (7, 'monetize', '限定オファー施策を設計して', '売上導線と継続率の両面で改善案を作れる', 7, 'advanced'),
  (7, 'monetize', '休眠ユーザー復帰施策を提案して', '売上導線と継続率の両面で改善案を作れる', 7, 'advanced'),
  (7, 'monetize', '初回課金率を上げる改善案を出して', '売上導線と継続率の両面で改善案を作れる', 7, 'advanced'),
  (7, 'monetize', '継続課金向けコンテンツ案を作って', '売上導線と継続率の両面で改善案を作れる', 7, 'advanced'),
  (7, 'monetize', '法人プラン提案資料の骨子を作って', '売上導線と継続率の両面で改善案を作れる', 7, 'advanced'),
  (7, 'monetize', '成約率計測KPIを定義して', '売上導線と継続率の両面で改善案を作れる', 7, 'advanced'),
  (7, 'monetize', 'A/Bテスト案を設計して', '売上導線と継続率の両面で改善案を作れる', 7, 'advanced'),
  (7, 'monetize', '営業トークを短文化して', '売上導線と継続率の両面で改善案を作れる', 7, 'advanced'),
  (7, 'monetize', 'クロスセル候補を抽出して', '売上導線と継続率の両面で改善案を作れる', 7, 'advanced'),
  (7, 'monetize', 'オンボーディング課金導線を作って', '売上導線と継続率の両面で改善案を作れる', 7, 'advanced'),
  (7, 'monetize', '成約までのボトルネックを分析して', '売上導線と継続率の両面で改善案を作れる', 7, 'advanced'),
  (7, 'monetize', '値上げ時の告知文を作って', '売上導線と継続率の両面で改善案を作れる', 7, 'advanced'),
  (8, 'marketing', 'この機能のLP見出しを10案作って', '集客文面を用途別に高速生成して施策化できる', 8, 'intermediate'),
  (8, 'marketing', 'SNS投稿文を3媒体向けに作って', '集客文面を用途別に高速生成して施策化できる', 8, 'intermediate'),
  (8, 'marketing', '広告用キャッチを20文字で作って', '集客文面を用途別に高速生成して施策化できる', 8, 'intermediate'),
  (8, 'marketing', 'リファラル訴求文を作って', '集客文面を用途別に高速生成して施策化できる', 8, 'intermediate'),
  (8, 'marketing', '再訪ユーザー向け通知文を作って', '集客文面を用途別に高速生成して施策化できる', 8, 'intermediate'),
  (8, 'marketing', '初回購入者向けフォロー文を作って', '集客文面を用途別に高速生成して施策化できる', 8, 'intermediate'),
  (8, 'marketing', '離脱ユーザー向け再提案文を作って', '集客文面を用途別に高速生成して施策化できる', 8, 'intermediate'),
  (8, 'marketing', '比較表の説明文を作って', '集客文面を用途別に高速生成して施策化できる', 8, 'intermediate'),
  (8, 'marketing', 'FAQの冒頭文を最適化して', '集客文面を用途別に高速生成して施策化できる', 8, 'intermediate'),
  (8, 'marketing', 'ケーススタディ紹介文を作って', '集客文面を用途別に高速生成して施策化できる', 8, 'intermediate'),
  (8, 'marketing', '導入メリットを3行でまとめて', '集客文面を用途別に高速生成して施策化できる', 8, 'intermediate'),
  (8, 'marketing', '業種別コピーを3種類作って', '集客文面を用途別に高速生成して施策化できる', 8, 'intermediate'),
  (8, 'marketing', '短尺動画用ナレーションを書いて', '集客文面を用途別に高速生成して施策化できる', 8, 'intermediate'),
  (8, 'marketing', 'メルマガ件名を10案出して', '集客文面を用途別に高速生成して施策化できる', 8, 'intermediate'),
  (8, 'marketing', 'セール告知文を丁寧語で作って', '集客文面を用途別に高速生成して施策化できる', 8, 'intermediate'),
  (8, 'marketing', 'ブランドストーリー文を作って', '集客文面を用途別に高速生成して施策化できる', 8, 'intermediate'),
  (8, 'marketing', 'CTA文言を5案作って', '集客文面を用途別に高速生成して施策化できる', 8, 'intermediate'),
  (8, 'marketing', '口コミ依頼メッセージを作って', '集客文面を用途別に高速生成して施策化できる', 8, 'intermediate'),
  (8, 'marketing', 'イベント告知テンプレを作って', '集客文面を用途別に高速生成して施策化できる', 8, 'intermediate');
